### ISSUE TITLE
Create an orientation blurb for modules, or a default set of training modules for new users.

### ISSUE THREAD

**Issue by lauratmercer** [LitSignal/publicissues#36]
Though we could upload a text document with an Overview/Instructions of how the owner of the module intends it to be used, I think it would be more user-friendly for learners (and would save one step for the person making the module) to have a text box where he/she could give instructions (eg - which articles are "must reads" and which are "additional info" or "we recommend watching this TedTalk then reading these two articles, etc")

**Comment by brianmacarthur** [comment]
It should be more obvious, but you can enter module settings (on the far right of the header area at beta.litsignal.com/username/module). On the settings page you can enter a short description or a more exhaustive README. As an example, I have both a description and a README in my module: https://beta.litsignal.com/brianmacarthur/ergodox-mechanical-keyboard

Maybe it would be a good idea to include a blurb at the top of every new module for the author with instruction about adding that information. Would that help? Or does something else come to mind?

**Comment by lauratmercer** [comment]
AhHa! found it... but yes, I think we could make it more obvious/easy to find.  I sometimes think of settings as the customizable but not crucial stuff (how I want my inbox organized, the defaults of size and type of font, color themes)... so it honestly didn't even hit my radar to click on settings until you pointed it out.  My brain was looking for it under the "edit components" link/menu.

**Comment by brianmacarthur** [comment]
There were some issues with the availability of the site over the last several days, so I apologize if you ran into them.

I have not yet created a default orientation module, which I think would be ideal, something that is prepopulated for every new user. In the meantime, I did make it easier to edit the README section directly from the module page by clicking on the Edit button. Thanks for that suggestion!

It might be nice to edit the description in the same way. Then the settings page could be limited to changing the title of the module, which I think should require an extra step since it changes the URL, and deleting the module. Let me know if you have any problems with what I've done or plan to do.

**Comment by brianmacarthur** [comment]
I went ahead and added module description to the fields that can be edited after clicking on the edit button. Now the settings button opens a page that allows users to change the title or delete the module. I will add tags to the editable fields later, but I am going to close this issue for now. 

I will be migrating the orientation module to Projects and will be open to suggestions there. Thanks!
